### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by METACMETAHA** [pontem-network/pontem#184] opened 2022-02-15 22:20 UTC
`pontem-node    | Hash: given=009fbe46db680acd4e5c78647801a25e470073d379cade26261affb64b9b88ea, expected=02635e1185c1c098658da0a440f73b6cea4b4f86de73f7d2458c0ce5dc7256c2
pontem-node    |
pontem-node    | ====================
pontem-node    |
pontem-node    | Version: 0.4.2-unknown-x86_64-linux-gnu
pontem-node    |
pontem-node    |    0: sp_panic_handler::set::{{closure}}
pontem-node    |    1: std::panicking::rust_panic_with_hook
pontem-node    |              at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5/library/std/src/panicking.rs:626:17
pontem-node    |    2: std::panicking::begin_panic::{{closure}}
pontem-node    |    3: std::sys_common::backtrace::__rust_end_short_backtrace
pontem-node    |    4: std::panicking::begin_panic
pontem-node    |    5: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::final_checks
pontem-node    |    6: tracing::span::Span::in_scope
pontem-node    |    7: frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPallets,COnRuntimeUpgrade>::execute_block
pontem-node    |    8: <pontem_runtime::Runtime as sp_api::runtime_decl_for_Core::Core<sp_runtime::generic::block::Block<sp_runtime::generic::header::Header<u32,sp_runtime::traits::BlakeTwo256>,sp_runtime::generic::unchecked_extrinsic::UncheckedExtrinsic<sp_runtime::multiaddress::MultiAddress<<<sp_runtime::MultiSignature as sp_runtime::traits::Verify>::Signer as sp_runtime::traits::IdentifyAccount>::AccountId,()>,pontem_runtime::Call,sp_runtime::MultiSignature,(frame_system::extensions::check_spec_version::CheckSpecVersion<pontem_runtime::Runtime>,frame_system::extensions::check_tx_version::CheckTxVersion<pontem_runtime::Runtime>,frame_system::extensions::check_genesis::CheckGenesis<pontem_runtime::Runtime>,frame_system::extensions::check_mortality::CheckMortality<pontem_runtime::Runtime>,frame_system::extensions::check_nonce::CheckNonce<pontem_runtime::Runtime>,frame_system::extensions::check_weight::CheckWeight<pontem_runtime::Runtime>,pallet_transaction_payment::ChargeTransactionPayment<pontem_runtime::Runtime>)>>>>::execute_block
pontem-node    |    9: std::panicking::try
pontem-node    |   10: std::thread::local::LocalKey<T>::with
pontem-node    |   11: sc_executor::native_executor::WasmExecutor::with_instance::{{closure}}
pontem-node    |   12: sc_executor::wasm_runtime::RuntimeCache::with_instance
pontem-node    |   13: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
pontem-node    |   14: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_aux
pontem-node    |   15: sp_state_machine::execution::StateMachine<B,H,N,Exec>::execute_using_consensus_failure_handler
pontem-node    |   16: <sc_service::client::call_executor::LocalCallExecutor<Block,B,E> as sc_client_api::call_executor::CallExecutor<Block>>::contextual_call
pontem-node    |   17: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
pontem-node    |   18: sp_api::runtime_decl_for_Core::execute_block_call_api_at
pontem-node    |   19: <pontem_runtime::RuntimeApiImpl<__SR_API_BLOCK__,RuntimeApiImplCall> as sp_api::Core<__SR_API_BLOCK__>>::Core_execute_block_runtime_api_impl
pontem-node    |   20: sp_api::Core::execute_block_with_context
pontem-node    |   21: sc_service::client::client::Client<B,E,Block,RA>::prepare_block_storage_changes
pontem-node    |   22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
pontem-node    |   23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
pontem-node    |   24: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
pontem-node    |   25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
pontem-node    |   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
pontem-node    |   27: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
pontem-node    |   28: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
pontem-node    |   29: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
pontem-node    |   30: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
pontem-node    |   31: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
pontem-node    |   32: tokio::runtime::enter::Enter::block_on
pontem-node    |   33: tokio::runtime::handle::Handle::block_on
pontem-node    |   34: tokio::runtime::task::core::CoreStage<T>::poll
pontem-node    |   35: tokio::runtime::task::harness::Harness<T,S>::poll
pontem-node    |   36: tokio::runtime::blocking::pool::Inner::run
pontem-node    |   37: std::sys_common::backtrace::__rust_begin_short_backtrace
pontem-node    |   38: core::ops::function::FnOnce::call_once{{vtable.shim}}
pontem-node    |   39: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
pontem-node    |              at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5/library/alloc/src/boxed.rs:1575:9
pontem-node    |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
pontem-node    |              at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5/library/alloc/src/boxed.rs:1575:9
pontem-node    |       std::sys::unix::thread::Thread::new::thread_start
pontem-node    |              at /rustc/e8cb1a4a567ce88e459ffd431207eff2e0f0ffa5/library/std/src/sys/unix/thread.rs:72:17
pontem-node    |   40: start_thread
pontem-node    |   41: clone
pontem-node    |
pontem-node    |
pontem-node    | Thread 'tokio-runtime-worker' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/57346f6/frame/executive/src/lib.rs:503
pontem-node    |
pontem-node    | This is a bug. Please report it at:
pontem-node    |
pontem-node    |        support.anonymous.an
pontem-node    |
pontem-node    |`

**Comment by METACMETAHA** [comment] 2022-02-15 22:25
So, this bug was repeated about 8 times during synchronization

**Comment by borispovod** [comment] 2022-02-25 01:54
@METACMETAHA try to use [restart script](https://github.com/pontem-network/bootstrap#optional-node-autorestart) for now, in the new version the issue is fixed, yet we need to do Runtime upgrades.

As issue discussed multiplay time closing for now

**Closed by borispovod** 2022-02-25 01:54 UTC
